FROM node:22-alpine

WORKDIR /app

# Copia i file delle dipendenze
COPY package*.json ./

# Installa le dipendenze
RUN npm install

# Esponi la porta usata da Angular
EXPOSE 4200

# Il comando per avviare il server di sviluppo, bindato su 0.0.0.0 per essere accessibile fuori dal container
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]
